name: Adds workload to the terraform yml

on: 
  workflow_dispatch:
    inputs:
       workload_name:
        description: 'Name of the workload to add'
        required: true

env:
  REPO_NAME: test-something
  BRANCH_NAME: "workloads/${{ inputs.workload_name }}"
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  change_file_and_create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add workload to file
      run: |
        bash ./scripts/add_workload.sh ${{ inputs.workload_name }} ${{ env.REPO_NAME }} ${{ secrets.GITHUB_TOKEN }} ${{ env.BRANCH_NAME }}

    - name: Push changes to new branch
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ env.BRANCH_NAME }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.11.0
      with:
        commit-message: "Update workloads"
        branch: ${{ env.BRANCH_NAME }}
        base: main
        title: "Update file"
        body: "Adds workload ${{ inputs.workload_name }} to the list"
        token: ${{ secrets.GITHUB_TOKEN }}