name: Adds workload to the terraform yml

on: 
  workflow_dispatch:
    inputs:
       workload_name:
        description: 'Name of the workload to add'
        required: true

jobs:
  change_file_and_create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add workload to file
      run: |
        bash ./scripts/add_workload.sh ${{ inputs.workload_name }} "test-something" ${{ secrets.GITHUB_TOKEN }} "workloads/${{ inputs.workload_name }}"
        cd "test-something"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.11.0
      with:
        commit-message: "Update workloads"
        branch: "workloads/${{ inputs.workload_name }}"
        base: main
        title: "Update file"
        body: "Adds workload ${{ inputs.workload_name }} to the list"
        token: ${{ secrets.GITHUB_TOKEN }}