name: Adds workload to the terraform yml

on: 
  workflow_dispatch:
    inputs:
       workload_name:
        description: 'Name of the workload to add'
        required: true

env:
  REPO_NAME: test-something
  YML_FILE_NAME: workload.yml
  BRANCH_NAME: "workloads/${{ inputs.workload_name }}"
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  change_file_and_create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Add workload to file
      shell: bash
      run: |
        yq e ".jobs.terraform.strategy.matrix.workload += [\"${{ inputs.workload_name }}\"]" -i "${{ env.YML_FILE_NAME }}"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "Update workloads"
        branch: ${{ env.BRANCH_NAME }}
        title: "Update file"
        body: "Adds workload ${{ inputs.workload_name }} to the list"
        token: ${{ env.GITHUB_TOKEN }}