name: Adds workload to the terraform yml

on: 
  workflow_dispatch:
    inputs:
       workload_name:
        description: 'Name of the workload to add'
        required: true

jobs:
  change_file_and_create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create new branch
      run: git checkout -b workload/${{ inputs.workload_name }}

    - name: Add workload to file
      run: |
        bash ./scripts/add_workload.sh ${{ inputs.workload_name }}

    - name: Commit changes
      run: |
        git config --global user.email "workload@conclusion.com"
        git config --global user.name "Workload user"
        git add .
        git commit -m "Added ${{ inputs.workload_name }}"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.11.0
      with:
        commit-message: "Update file"
        branch: "main"
        title: "Update file"
        body: "This pull request updates the file with new content."
        token: ${{ secrets.GITHUB_TOKEN }}